name: Roblox FFlag Tracker

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run updateff
        run: python updateff.py

      - name: Debug output folder
        run: ls -R ${{ github.workspace }}/output || echo "No output folder found"

      - name: Publish reports to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_branch: gh-pages
         publish_dir: ./output
         force_orphan: true 

